package T145.elementalcreepers;

import T145.elementalcreepers.proxies.CommonProxy;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod(modid = ElementalCreepers.MODID, name = ElementalCreepers.NAME, version = ElementalCreepers.VERSION, updateJSON = ElementalCreepers.UPDATE_JSON)
public class ElementalCreepers {

    public static final String MODID = "elementalcreepers";
    public static final String NAME = "ElementalCreepers";
    public static final Logger LOG = LogManager.getLogger(MODID);
    static final String VERSION = "@VERSION@";
    static final String UPDATE_JSON = "https://raw.githubusercontent.com/T145/elemental-creepers/master/update.json";
    private static final String COMMON_PROXY = "T145.elementalcreepers.proxies.CommonProxy";
    private static final String CLIENT_PROXY = "T145.elementalcreepers.proxies.ClientProxy";

    @Instance(MODID)
    public static ElementalCreepers instance;

    @SidedProxy(serverSide = COMMON_PROXY, clientSide = CLIENT_PROXY)
    public static CommonProxy proxy;

    @Metadata
    private ModMetadata meta;

    public static SimpleNetworkWrapper network;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        meta.authorList.add("T145");
        meta.autogenerated = false;
        meta.credits = "The fans!";
        meta.description = "Here comes the BOOM!";
        meta.logoFile = "logo.png";
        meta.modId = MODID;
        meta.name = NAME;
        meta.url = "https://github.com/T145/elemental-creepers";
        meta.useDependencyInformation = false;
        meta.version = VERSION;
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {}

    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {}
}